### ISSUE TITLE
Firmware error

### ISSUE THREAD

**Issue by Monica2511** [IntelRealSense/RealSenseID#112]
Hi, i have a F455 camera and i'm using windows 10, i downloaded installer v0.23 for windows. I started realsenseid-viewer  program and got Device Error and require to update firmware. I update newest version fw 4.2.1 and then got this:
![image](https://user-images.githubusercontent.com/46559607/127991623-61956f1c-aa14-4c0c-967c-cdcaf6313171.png)
I have followed this requirement with fw 3.1 version but got another error: 
![image](https://user-images.githubusercontent.com/46559607/127991955-3fbdd57b-4caf-4363-b545-025a0f806f1f.png)
What can i do to fix this problem, thanks.
P/s: there are 2 firmware files i have used to upgrade 
v4.2.1: F450_4.2.1.8201_SKU1_SIGNED.bin
v3.1.0.29: F450_3.1.0.29_SKU1_SIGNED.bin

**Comment by zeynepkoyun** [comment]
Hi @Monica2511 
I got a similar error for ubuntu 16.04 as a solution when I researched;
As seen in the commands below, the problem was solved by first updating the 3.1.29 version and then to the 4.2.0 version.

./rsid-fw-update --file F450_3.1.0.29_SKU1_SIGNED.bin --port /dev/ttyACM0 --force-version
./rsid-fw-update --file F450_4.2.0.8200_SKU1_SIGNED.bin --port /dev/ttyACM0
